### ISSUE TITLE
九敏！！佬来看看

### ISSUE THREAD

**Issue by hutao01-miku** [coderxi1/mirai-sdwebui-client#2]
小白想知道怎么让机器人自己对自己说的话画图，我给全部人权限，用机器人自己说指令还是显示没有权限，想知道怎么开这个

**Comment by hutao01-miku** [comment]
默认设定在哪里阿，代码里找不到

**Comment by hutao01-miku** [comment]
还有tag，识别很不准确，tag过多时生成的都不相关，在电脑上和机器人上相同的tag差距太大了，这个有解决办法吗？问题太多了，抱歉。

**Comment by coderxi1** [comment]
感觉这个使用场景有些不太优雅。。真要这么用的话还是搞两个bot吧 :-(
