### ISSUE TITLE
"enable_hr=true" is not work

### ISSUE THREAD

**Issue by pzzmyc** [coderxi1/mirai-sdwebui-client#4]
This is the command sent in the chat：
/sd txt2img
prompt=nuclear explosion
negative=noise,extra digit,low details,worst quality,white background,
steps=30
width=1024
height=1200
sampler=DPM++ 2M Karras
cfg_scale=6
enable_hr=true
denoising_strength=0.4
hr_scale=1.7
hr_upscaler=R-ESRGAN 4x+

This is  error message：
![image](https://github.com/coderxi1/mirai-sdwebui-client/assets/43562427/de9bb4fe-4aca-4daa-b2e0-c54cfc662456)

**Comment by coderxi1** [comment]
抱歉，疏忽了对bool类型的转换，由于好久没搞机器人所以忘记了这个插件... [0.1.2](https://github.com/coderxi1/mirai-sdwebui-client/releases/tag/0.1.2) 已修复
