### ISSUE TITLE
SDWebUI生成的图片文件在那里 怎么让它保存

### ISSUE THREAD

**Issue by Young-Ginger** [coderxi1/mirai-sdwebui-client#5]
生成的图片不会在SDWebUI下生成文件 加了保存图片这个参数也没有 是没法保存还是有别的参数

**Comment by coderxi1** [comment]
抱歉，疏忽了对bool类型的转换，由于好久没搞机器人所以忘记了这个项目... 现在可以使用 `保存图片=true` 来保存，保存路径在stable-diffusion-webui 根目录的 outputs\txt2img-images 和 outputs\img2img-images
